name: Container Image Release

on: [push]

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2

      - name: Get Path To Substrate Contracts Node
        run: readlink -f build-contract-node-docker.sh

      - name: Build Image
        run: bash /home/runner/work/substrate-contracts-node/substrate-contracts-node/build-contract-node-docker.sh

      - name: Install docker-slim
        run: curl -sL https://raw.githubusercontent.com/docker-slim/docker-slim/master/scripts/install-dockerslim.sh | sudo -E bash -
      - name: Slim down the Image
        run: docker-slim build --target webb-tools/substrate-contracts-node --http-probe-off --entrypoint substrate-contracts-node
      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/substrate-contracts-node
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          # Use Docker `edge` tag convention
          [ "$VERSION" == "main" ] && VERSION=edge
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag webb-tools/substrate-contracts-node.slim $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
